const Homeproduct = 
[
    {
        id: 1,
        Name: "Kales",
        Price: 1,
        image: "images/Screenshot (351).png",
        cat: 'Vegetables',
        type: 'featured',
    },
    {
        id: 2,
        Name: "colliander/Dania",
        Price: 2,
        image: "images/Screenshot (333).png",
        cat: 'spices',
        type: 'top',
    },
    {
        id: 3,
        Name: "Carrots",
        Price: 3,
        image: "images/Screenshot (336).png",
        cat: 'Spices',
        type: 'top',
    },
    {
        id: 4,
        Name: "Ginger",
        Price: 30,
        image: "images/Screenshot (335).png",
        cat: 'ginger',
        type: 'top',
    },
    {
        id: 5,
        Name: "Eggs",
        Price: 40,
        image: "images/Screenshot (337).png",
        cat: 'Eggs',
        type: 'Eggs',
    },
    {
        id: 6,
        Name: "mangoes",
        Price: 70,
        image: "images/Screenshot (331).png",
        cat: 'Fruits',
        type: 'new',
    },
    {
        id: 7,
        Name: "pomegranate/Tunda damu",
        Price: 100,
        image: "images/Screenshot (332).png",
        cat: 'Fruits',
        type: 'new',
    },
    {
        id: 8,
        Name: "Garlic/Kitunguu Saumu",
        Price: 600,
        image: "images/Screenshot (334).png",
        cat: 'Spices',
        type: 'top',
    },
    {
        id: 9,
        Name: "Spinach",
        Price: 20,
        image: "images/Screenshot (356).png",
        cat: 'Vegetables',
        type: 'new',
    },
    {
        id: 10,
        Name: "Cabbage",
        Price: 50,
        image: "images/Screenshot (353).png",
        cat: 'Vegetables',
        type: 'new',
    },
    {
        id: 11,
        Name: "Tomatoes",
        Price: 30,
        image: "images/Screenshot (333).png",
        cat: 'Fruits',
        type: 'featured',
    },
    {
        id: 12,
        Name: "Potatoes/viazi",
        Price: 100,
        image: "images/Screenshot (354).png",
        cat: 'potatoes',
        type: 'potatoes',
    },
    {
        id: 13,
        Name: "Bananas",
        Price: 100,
        image: "images/Screenshot (314).png",
        cat: 'Fruits',
        type: 'featured',
    },
    
];

export default Homeproduct;
